-- database/bookstore.sql
CREATE TABLE IF NOT EXISTS books (
    id INT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(200) NOT NULL,
    author VARCHAR(200) NOT NULL,
    price DECIMAL(10,2) NOT NULL,
    category VARCHAR(100),
    description TEXT,
    image VARCHAR(255),
    quantity INT NOT NULL DEFAULT 1 CHECK (quantity >= 0),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- If you already have an older books table, run these ALTER statements once:
-- ALTER TABLE books MODIFY COLUMN title VARCHAR(200) NOT NULL;
-- ALTER TABLE books MODIFY COLUMN author VARCHAR(200) NOT NULL;
-- ALTER TABLE books MODIFY COLUMN price DECIMAL(10,2) NOT NULL;
-- ALTER TABLE books MODIFY COLUMN quantity INT NOT NULL DEFAULT 1;
-- ALTER TABLE books MODIFY COLUMN image VARCHAR(255);
-- ALTER TABLE books ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
-- ALTER TABLE books ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

CREATE TABLE IF NOT EXISTS admin_profiles (
    user_id INT PRIMARY KEY,
    phone VARCHAR(50),
    address VARCHAR(255),
    image VARCHAR(255),
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_profiles (
    user_id INT PRIMARY KEY,
    image VARCHAR(255),
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sales (
    id INT PRIMARY KEY AUTO_INCREMENT,
    book_id INT NOT NULL,
    book_title VARCHAR(255) NOT NULL,
    buyer_name VARCHAR(200),
    buyer_email VARCHAR(200),
    quantity INT NOT NULL,
    unit_price DECIMAL(10,2) NOT NULL,
    total_amount DECIMAL(10,2) NOT NULL,
    purchased_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
